### PR TITLE
chore: remove waku dep from @waku/interfaces by defining IEnr

### PR DESCRIPTION
**Pull request by fryorcraken**
@waku packages are expected to (dev)depend on @waku/interfaces to implement them. Hence, to avoid possible cyclic (dev)dependency, define IEnr interface and use it as a type across @waku/packages.

### CODE REVIEW

**Comment by danisharora099** [comment]
Wouldn't this create redundancy causing redeclarations?

Which package is suffering from cyclic dependency with `/interfaces`?

**Comment by fryorcraken** [comment]
> Wouldn't this create redundancy causing redeclarations?

What redeclaration?

> Which package is suffering from cyclic dependency with `/interfaces`?

There is no cyclic dependency currently.

`@waku/interfaces` defines interfaces which enables other packages to share type definitions with no risk of cyclic dependencies.
By adding `@waku/enr` as a dependency to `@waku/interfaces`, we break this intentional design and now there is a risk of creating a cyclic dependency.

Because `@waku/interfaces` is here to define common types, then it be a root to the dependency tree: other packages depends on it, it does not depend on any package.

**Review by danisharora099 — APPROVED** [review]
lgtm!

**Comment by danisharora099** [comment]
> > Wouldn't this create redundancy causing redeclarations?
> 
> What redeclaration?
> 
> > Which package is suffering from cyclic dependency with `/interfaces`?
> 
> There is no cyclic dependency currently.
> 
> `@waku/interfaces` defines interfaces which enables other packages to share type definitions with no risk of cyclic dependencies. By adding `@waku/enr` as a dependency to `@waku/interfaces`, we break this intentional design and now there is a risk of creating a cyclic dependency.
> 
> Because `@waku/interfaces` is here to define common types, then it be a root to the dependency tree: other packages depends on it, it does not depend on any package.

I misinterpreted the scope of this PR earlier - looks good :)

**Pull request merged**
