### PR TITLE
feat: Add github action for publishing packages tagged as dev

### PR DESCRIPTION
**Pull request by adklempner**
## Problem

Current github actions only allows publishing a pre-release package based off master, tagged as next

## Solution

 

Add an action that allows manually publishing the package based off any branch, tagged as dev

### CODE REVIEW

**Comment by weboko** [comment]
General question: we don't need `rc` if we have `dev` so let's keep only one. 
I think changing existing pipeline with `dev` tag would be a way to go. 

Wdyt?

**Review by danisharora099 — APPROVED** [review]

**Review by weboko — CHANGES_REQUESTED** [review]
let's not merge before we discuss https://github.com/waku-org/js-waku/pull/1777#issuecomment-1884737111

**Comment by adklempner** [comment]
> General question: we don't need `rc` if we have `dev` so let's keep only one. I think changing existing pipeline with `dev` tag would be a way to go.
> 
> Wdyt?

@weboko I updated the commit to use `next` instead of `dev`. So both actions now use the same tag.

**Comment by weboko** [comment]
Closing as it was resolved in https://github.com/waku-org/js-waku/pull/1915/commits/359b1977026b26357766b99e11960ee7bda22044

**Pull request closed without merging**
