### PR TITLE
chore: release master

### PR DESCRIPTION
**Pull request by fryorcraken**
:robot: I have created a release *beep* *boop*
---

<details><summary>core: 0.0.22</summary>

### Bug Fixes

* Refactors message decoding to abort as soon as a suitable decoder found ([#1414](https://github.com/waku-org/js-waku/issues/1414)) ([30fcace](https://github.com/waku-org/js-waku/commit/30fcacea84d9aefbe71e7f4b48506a088f2e1bf8))
</details>

<details><summary>@waku/message-encryption: 0.0.20</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/core bumped from 0.0.21 to 0.0.22
</details>

<details><summary>@waku/peer-exchange: 0.0.15</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/core bumped from 0.0.21 to 0.0.22
</details>

<details><summary>@waku/relay: 0.0.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/core bumped from 0.0.21 to 0.0.22
</details>

<details><summary>@waku/sdk: 0.0.18</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/relay bumped from 0.0.4 to 0.0.5
    * @waku/core bumped from 0.0.21 to 0.0.22
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by weboko — APPROVED** [review]

**Comment by fryorcraken** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/peer-exchange-v0.0.15 :sunflower:

**Comment by fryorcraken** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/message-encryption-v0.0.20 :sunflower:

**Comment by fryorcraken** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/sdk-v0.0.18 :sunflower:

**Comment by fryorcraken** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/relay-v0.0.5 :sunflower:

**Pull request merged**
