### PR TITLE
feat!: add `meta` field on Waku Message and provide setter and validation interfaces

### PR DESCRIPTION
**Pull request by fryorcraken**
Ref: #1208

### CODE REVIEW

**Comment by fryorcraken** [comment]
Cc @felicio

**Comment by fryorcraken** [comment]
Note: can be reviewed by patches (first adds encoding, second adds decoding)

**Comment by fryorcraken** [comment]
access to pubsub topic is needed for deterministic message hashing so more change are needed.

**Comment by fryorcraken** [comment]
The validation interface is actually too pre-emptive. I assumed for some reason that the MUID would be stored in `meta` and hence message integrity would be checked for a given application/pubsub topic.

Reading https://github.com/waku-org/pm/issues/9 more closely, this is incorrect.

`meta` is an application specific field. The usage is not yet defined. I believe it's likely to be a signature for Status Communities?

**Review by weboko — APPROVED** [review]
Looks a bit complicated but good to me!

**Comment by fryorcraken** [comment]
Superseded by  #1238

Will wait to get more context before adding the `isMetaValid` helper.

**Pull request closed without merging**
