### PR TITLE
chore: release master

### PR DESCRIPTION
**Pull request by weboko**
:robot: I have created a release *beep* *boop*
---

<details><summary>core: 0.0.33</summary>

### Features

* **filter:** Enhancing protocol peer management with mutex locks  ([#2137](https://github.com/waku-org/js-waku/issues/2137)) ([b2efce5](https://github.com/waku-org/js-waku/commit/b2efce5ec27807325685cc32f9333805e6321ac7))
* **lightPush:** Improve peer usage and improve readability ([#2155](https://github.com/waku-org/js-waku/issues/2155)) ([1d68526](https://github.com/waku-org/js-waku/commit/1d68526e724155f76bb786239f475a774115ee97))

### Bug Fixes

* Peer renewal connection drop & stream management ([#2145](https://github.com/waku-org/js-waku/issues/2145)) ([b93134a](https://github.com/waku-org/js-waku/commit/b93134a517006d3850ef13c1290194767ce40c21))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/enr bumped from ^0.0.26 to ^0.0.27
    * @waku/interfaces bumped from 0.0.27 to 0.0.28
    * @waku/utils bumped from 0.0.20 to 0.0.21
</details>

<details><summary>discovery: 0.0.6</summary>

### Features

* **filter:** Enhancing protocol peer management with mutex locks  ([#2137](https://github.com/waku-org/js-waku/issues/2137)) ([b2efce5](https://github.com/waku-org/js-waku/commit/b2efce5ec27807325685cc32f9333805e6321ac7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/interfaces bumped from 0.0.27 to 0.0.28
    * @waku/enr bumped from 0.0.26 to 0.0.27
    * @waku/core bumped from 0.0.32 to 0.0.33
    * @waku/utils bumped from 0.0.20 to 0.0.21
</details>

<details><summary>@waku/enr: 0.0.27</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/utils bumped from 0.0.20 to 0.0.21
  * devDependencies
    * @waku/interfaces bumped from 0.0.27 to 0.0.28
</details>

<details><summary>interfaces: 0.0.28</summary>

### ⚠ BREAKING CHANGES

* lighten retry logic for LightPush ([#2182](https://github.com/waku-org/js-waku/issues/2182))

### Features

* **filter:** Enhancing protocol peer management with mutex locks  ([#2137](https://github.com/waku-org/js-waku/issues/2137)) ([b2efce5](https://github.com/waku-org/js-waku/commit/b2efce5ec27807325685cc32f9333805e6321ac7))
* **filter:** Reliability monitor as a separate class to handle reliability logic ([#2117](https://github.com/waku-org/js-waku/issues/2117)) ([7ad1d32](https://github.com/waku-org/js-waku/commit/7ad1d321ca7f17bfeb54618d03580c4223f1b485))
* Lighten retry logic for LightPush ([#2182](https://github.com/waku-org/js-waku/issues/2182)) ([4049123](https://github.com/waku-org/js-waku/commit/4049123f147f24dfca35c584bd925d9892d4b518))
* **lightPush:** Improve peer usage and improve readability ([#2155](https://github.com/waku-org/js-waku/issues/2155)) ([1d68526](https://github.com/waku-org/js-waku/commit/1d68526e724155f76bb786239f475a774115ee97))
* Replace `waitForRemotePeers()` with `waku.waitForPeer()` method ([#2161](https://github.com/waku-org/js-waku/issues/2161)) ([75fcca4](https://github.com/waku-org/js-waku/commit/75fcca4cd99d6aabcbb14afab9332c98ddc6b74f))

### Bug Fixes

* Attempt to fix some of the Filter issues  ([#2183](https://github.com/waku-org/js-waku/issues/2183)) ([ded994f](https://github.com/waku-org/js-waku/commit/ded994f8ecd4ebec05cb9760f7eb3da273e5e02b))
</details>

<details><summary>@waku/message-encryption: 0.0.31</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/core bumped from 0.0.32 to 0.0.33
    * @waku/interfaces bumped from 0.0.27 to 0.0.28
    * @waku/utils bumped from 0.0.20 to 0.0.21
</details>

<details><summary>message-hash: 0.1.17</summary>

### Bug Fixes

* Attempt to fix some of the Filter issues  ([#2183](https://github.com/waku-org/js-waku/issues/2183)) ([ded994f](https://github.com/waku-org/js-waku/commit/ded994f8ecd4ebec05cb9760f7eb3da273e5e02b))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/utils bumped from 0.0.20 to 0.0.21
  * devDependencies
    * @waku/interfaces bumped from 0.0.27 to 0.0.28
</details>

<details><summary>relay: 0.0.16</summary>

### Features

* Replace `waitForRemotePeers()` with `waku.waitForPeer()` method ([#2161](https://github.com/waku-org/js-waku/issues/2161)) ([75fcca4](https://github.com/waku-org/js-waku/commit/75fcca4cd99d6aabcbb14afab9332c98ddc6b74f))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/core bumped from 0.0.32 to 0.0.33
    * @waku/sdk bumped from 0.0.28 to 0.0.29
    * @waku/interfaces bumped from 0.0.27 to 0.0.28
    * @waku/utils bumped from 0.0.20 to 0.0.21
</details>

<details><summary>sdk: 0.0.29</summary>

### ⚠ BREAKING CHANGES

* lighten retry logic for LightPush ([#2182](https://github.com/waku-org/js-waku/issues/2182))

### Features

* Confirm metadata and protocols needed in waitForRemotePeer ([#2160](https://github.com/waku-org/js-waku/issues/2160)) ([d37e024](https://github.com/waku-org/js-waku/commit/d37e0245cf265697d89319b5efb1e5535af30cd5))
* **filter:** Enhancing protocol peer management with mutex locks  ([#2137](https://github.com/waku-org/js-waku/issues/2137)) ([b2efce5](https://github.com/waku-org/js-waku/commit/b2efce5ec27807325685cc32f9333805e6321ac7))
* **filter:** Reliability monitor as a separate class to handle reliability logic ([#2117](https://github.com/waku-org/js-waku/issues/2117)) ([7ad1d32](https://github.com/waku-org/js-waku/commit/7ad1d321ca7f17bfeb54618d03580c4223f1b485))
* Lighten retry logic for LightPush ([#2182](https://github.com/waku-org/js-waku/issues/2182)) ([4049123](https://github.com/waku-org/js-waku/commit/4049123f147f24dfca35c584bd925d9892d4b518))
* **lightPush:** Improve peer usage and improve readability ([#2155](https://github.com/waku-org/js-waku/issues/2155)) ([1d68526](https://github.com/waku-org/js-waku/commit/1d68526e724155f76bb786239f475a774115ee97))
* **lightpush:** Introduce ReliabilityMonitor and allow `send` retries ([#2130](https://github.com/waku-org/js-waku/issues/2130)) ([7a6247c](https://github.com/waku-org/js-waku/commit/7a6247cb7081e8b9b1d48c24040aae63144457aa))
* Replace `waitForRemotePeers()` with `waku.waitForPeer()` method ([#2161](https://github.com/waku-org/js-waku/issues/2161)) ([75fcca4](https://github.com/waku-org/js-waku/commit/75fcca4cd99d6aabcbb14afab9332c98ddc6b74f))

### Bug Fixes

* Attempt to fix some of the Filter issues  ([#2183](https://github.com/waku-org/js-waku/issues/2183)) ([ded994f](https://github.com/waku-org/js-waku/commit/ded994f8ecd4ebec05cb9760f7eb3da273e5e02b))
* Peer renewal connection drop & stream management ([#2145](https://github.com/waku-org/js-waku/issues/2145)) ([b93134a](https://github.com/waku-org/js-waku/commit/b93134a517006d3850ef13c1290194767ce40c21))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/core bumped from 0.0.32 to 0.0.33
    * @waku/discovery bumped from 0.0.5 to 0.0.6
    * @waku/interfaces bumped from 0.0.27 to 0.0.28
    * @waku/utils bumped from 0.0.20 to 0.0.21
    * @waku/message-hash bumped from 0.1.16 to 0.1.17
</details>

<details><summary>utils: 0.0.21</summary>

### Features

* **filter:** Enhancing protocol peer management with mutex locks  ([#2137](https://github.com/waku-org/js-waku/issues/2137)) ([b2efce5](https://github.com/waku-org/js-waku/commit/b2efce5ec27807325685cc32f9333805e6321ac7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/interfaces bumped from 0.0.27 to 0.0.28
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by adklempner — APPROVED** [review]

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/utils-v0.0.21 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/enr-v0.0.27 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/core-v0.0.33 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/message-encryption-v0.0.31 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/sdk-v0.0.29 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/relay-v0.0.16 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/discovery-v0.0.6 :sunflower:

**Pull request merged**
