### PR TITLE
chore: release master

### PR DESCRIPTION
**Pull request by weboko**
:robot: I have created a release *beep* *boop*
---

<details><summary>core: 0.0.27</summary>

### ⚠ BREAKING CHANGES

* protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756))

### Features

* Create node and subscription by content topic ([ee2d417](https://github.com/waku-org/js-waku/commit/ee2d4176f8cca45a51b7dac0009f0eb01952f540))
* Decouple sharding params out of core ([e138b4f](https://github.com/waku-org/js-waku/commit/e138b4f5c49a35a37830e31e8be87d824f53249f))
* Lightpush & filter send requests to multiple peers ([#1779](https://github.com/waku-org/js-waku/issues/1779)) ([7affbe2](https://github.com/waku-org/js-waku/commit/7affbe222dd30ccb6619839f4bc5eb86433a80f7))
* Local discovery ([#1811](https://github.com/waku-org/js-waku/issues/1811)) ([199f6ab](https://github.com/waku-org/js-waku/commit/199f6ab2ff83694b93e94e935e2925537e01e281))
* Make ShardingParams optional in sdk, required internally ([68d3229](https://github.com/waku-org/js-waku/commit/68d3229644f395bd84b2e2a7067c7b51e9da3dd0))
* Protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756)) ([477c2a5](https://github.com/waku-org/js-waku/commit/477c2a5918f2f75cd2c14bc6ed75e1687c5a09b4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/enr bumped from ^0.0.20 to ^0.0.21
    * @waku/interfaces bumped from 0.0.21 to 0.0.22
    * @waku/message-hash bumped from ^0.1.10 to ^0.1.11
    * @waku/utils bumped from 0.0.14 to 0.0.15
</details>

<details><summary>dns-discovery: 0.0.21</summary>

### ⚠ BREAKING CHANGES

* protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756))

### Features

* Protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756)) ([477c2a5](https://github.com/waku-org/js-waku/commit/477c2a5918f2f75cd2c14bc6ed75e1687c5a09b4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/enr bumped from 0.0.20 to 0.0.21
    * @waku/utils bumped from 0.0.14 to 0.0.15
  * devDependencies
    * @waku/interfaces bumped from 0.0.21 to 0.0.22
</details>

<details><summary>enr: 0.0.21</summary>

### ⚠ BREAKING CHANGES

* protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756))

### Features

* Protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756)) ([477c2a5](https://github.com/waku-org/js-waku/commit/477c2a5918f2f75cd2c14bc6ed75e1687c5a09b4))

### Bug Fixes

* **tests:** Append `p2p` with the multiaddrs from ENR ([#1817](https://github.com/waku-org/js-waku/issues/1817)) ([f8e02ab](https://github.com/waku-org/js-waku/commit/f8e02ab19eefd616926e17900602dcef28b068ff))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/utils bumped from 0.0.14 to 0.0.15
  * devDependencies
    * @waku/interfaces bumped from 0.0.21 to 0.0.22
</details>

<details><summary>interfaces: 0.0.22</summary>

### ⚠ BREAKING CHANGES

* rename local-discovery to local-peer-cache-discovery ([#1867](https://github.com/waku-org/js-waku/issues/1867))
* protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756))

### Features

* Add bootstrapPeers option and refactor sdk ([#1871](https://github.com/waku-org/js-waku/issues/1871)) ([9f198dd](https://github.com/waku-org/js-waku/commit/9f198dd149ef299e3edce69b93cc2942c6f24846))
* Create node and subscription by content topic ([ee2d417](https://github.com/waku-org/js-waku/commit/ee2d4176f8cca45a51b7dac0009f0eb01952f540))
* Decouple sharding params out of core ([e138b4f](https://github.com/waku-org/js-waku/commit/e138b4f5c49a35a37830e31e8be87d824f53249f))
* Lightpush & filter send requests to multiple peers ([#1779](https://github.com/waku-org/js-waku/issues/1779)) ([7affbe2](https://github.com/waku-org/js-waku/commit/7affbe222dd30ccb6619839f4bc5eb86433a80f7))
* Local discovery ([#1811](https://github.com/waku-org/js-waku/issues/1811)) ([199f6ab](https://github.com/waku-org/js-waku/commit/199f6ab2ff83694b93e94e935e2925537e01e281))
* Make ShardingParams optional in sdk, required internally ([68d3229](https://github.com/waku-org/js-waku/commit/68d3229644f395bd84b2e2a7067c7b51e9da3dd0))
* Protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756)) ([477c2a5](https://github.com/waku-org/js-waku/commit/477c2a5918f2f75cd2c14bc6ed75e1687c5a09b4))

### Miscellaneous Chores

* Rename local-discovery to local-peer-cache-discovery ([#1867](https://github.com/waku-org/js-waku/issues/1867)) ([f3cb10d](https://github.com/waku-org/js-waku/commit/f3cb10d484bac134377b8cfd77e077ffc33bd319))
</details>

<details><summary>local-peer-cache-discovery: 1.0.0</summary>

### ⚠ BREAKING CHANGES

* rename local-discovery to local-peer-cache-discovery ([#1867](https://github.com/waku-org/js-waku/issues/1867))

### Miscellaneous Chores

* Rename local-discovery to local-peer-cache-discovery ([#1867](https://github.com/waku-org/js-waku/issues/1867)) ([f3cb10d](https://github.com/waku-org/js-waku/commit/f3cb10d484bac134377b8cfd77e077ffc33bd319))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/interfaces bumped from ^0.0.21 to ^0.0.22
    * @waku/utils bumped from ^0.0.14 to ^0.0.15
</details>

<details><summary>@waku/message-encryption: 0.0.25</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/core bumped from 0.0.26 to 0.0.27
    * @waku/interfaces bumped from 0.0.21 to 0.0.22
    * @waku/utils bumped from 0.0.14 to 0.0.15
</details>

<details><summary>message-hash: 0.1.11</summary>

### Features

* Lightpush & filter send requests to multiple peers ([#1779](https://github.com/waku-org/js-waku/issues/1779)) ([7affbe2](https://github.com/waku-org/js-waku/commit/7affbe222dd30ccb6619839f4bc5eb86433a80f7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/utils bumped from 0.0.14 to 0.0.15
  * devDependencies
    * @waku/interfaces bumped from 0.0.21 to 0.0.22
</details>

<details><summary>peer-exchange: 0.0.20</summary>

### ⚠ BREAKING CHANGES

* protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756))

### Features

* Decouple sharding params out of core ([e138b4f](https://github.com/waku-org/js-waku/commit/e138b4f5c49a35a37830e31e8be87d824f53249f))
* Protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756)) ([477c2a5](https://github.com/waku-org/js-waku/commit/477c2a5918f2f75cd2c14bc6ed75e1687c5a09b4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/core bumped from 0.0.26 to 0.0.27
    * @waku/enr bumped from 0.0.20 to 0.0.21
    * @waku/interfaces bumped from 0.0.21 to 0.0.22
    * @waku/utils bumped from 0.0.14 to 0.0.15
</details>

<details><summary>relay: 0.0.10</summary>

### Features

* Decouple sharding params out of core ([e138b4f](https://github.com/waku-org/js-waku/commit/e138b4f5c49a35a37830e31e8be87d824f53249f))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/core bumped from 0.0.26 to 0.0.27
    * @waku/interfaces bumped from 0.0.21 to 0.0.22
    * @waku/utils bumped from 0.0.14 to 0.0.15
</details>

<details><summary>sdk: 0.0.23</summary>

### ⚠ BREAKING CHANGES

* rename local-discovery to local-peer-cache-discovery ([#1867](https://github.com/waku-org/js-waku/issues/1867))
* discourage the use of relay in browsers ([#1778](https://github.com/waku-org/js-waku/issues/1778))

### Features

* Add bootstrapPeers option and refactor sdk ([#1871](https://github.com/waku-org/js-waku/issues/1871)) ([9f198dd](https://github.com/waku-org/js-waku/commit/9f198dd149ef299e3edce69b93cc2942c6f24846))
* Create node and subscription by content topic ([ee2d417](https://github.com/waku-org/js-waku/commit/ee2d4176f8cca45a51b7dac0009f0eb01952f540))
* Decouple sharding params out of core ([e138b4f](https://github.com/waku-org/js-waku/commit/e138b4f5c49a35a37830e31e8be87d824f53249f))
* Local discovery ([#1811](https://github.com/waku-org/js-waku/issues/1811)) ([199f6ab](https://github.com/waku-org/js-waku/commit/199f6ab2ff83694b93e94e935e2925537e01e281))
* Make ShardingParams optional in sdk, required internally ([68d3229](https://github.com/waku-org/js-waku/commit/68d3229644f395bd84b2e2a7067c7b51e9da3dd0))

### Miscellaneous Chores

* Discourage the use of relay in browsers ([#1778](https://github.com/waku-org/js-waku/issues/1778)) ([906c933](https://github.com/waku-org/js-waku/commit/906c93329e4094c79e3f7f5c56e1b78afd778e1a))
* Rename local-discovery to local-peer-cache-discovery ([#1867](https://github.com/waku-org/js-waku/issues/1867)) ([f3cb10d](https://github.com/waku-org/js-waku/commit/f3cb10d484bac134377b8cfd77e077ffc33bd319))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/core bumped from 0.0.26 to 0.0.27
    * @waku/dns-discovery bumped from 0.0.20 to 0.0.21
    * @waku/interfaces bumped from 0.0.21 to 0.0.22
    * @waku/local-peer-cache-discovery bumped from ^0.0.1 to ^1.0.0
    * @waku/peer-exchange bumped from ^0.0.19 to ^0.0.20
    * @waku/relay bumped from 0.0.9 to 0.0.10
    * @waku/utils bumped from 0.0.14 to 0.0.15
</details>

<details><summary>utils: 0.0.15</summary>

### ⚠ BREAKING CHANGES

* protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756))

### Features

* Decouple sharding params out of core ([e138b4f](https://github.com/waku-org/js-waku/commit/e138b4f5c49a35a37830e31e8be87d824f53249f))
* Local discovery ([#1811](https://github.com/waku-org/js-waku/issues/1811)) ([199f6ab](https://github.com/waku-org/js-waku/commit/199f6ab2ff83694b93e94e935e2925537e01e281))
* Make ShardingParams optional in sdk, required internally ([68d3229](https://github.com/waku-org/js-waku/commit/68d3229644f395bd84b2e2a7067c7b51e9da3dd0))
* Protocols filter peers as per configured shard ([#1756](https://github.com/waku-org/js-waku/issues/1756)) ([477c2a5](https://github.com/waku-org/js-waku/commit/477c2a5918f2f75cd2c14bc6ed75e1687c5a09b4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @waku/interfaces bumped from 0.0.21 to 0.0.22
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by adklempner — APPROVED** [review]

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/utils-v0.0.15 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/interfaces-v0.0.22 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/message-hash-v0.1.11 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/peer-exchange-v0.0.20 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/core-v0.0.27 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/dns-discovery-v0.0.21 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/message-encryption-v0.0.25 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/sdk-v0.0.23 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/relay-v0.0.10 :sunflower:

**Comment by weboko** [comment]
:robot: Release is at https://github.com/waku-org/js-waku/releases/tag/local-peer-cache-discovery-v1.0.0 :sunflower:

**Pull request merged**
