### PR TITLE
fix: catch top level exception when preemptively creating streams

### LINKED ISSUE #1569: Unhandled rejection when calling lightPush send
This is a **bug report**

## Problem

I have a long running Node.js application (think of a chat bot) that uses waku lightPush. Occasionally there are some uncaught rejections caught at the top-level when invoking `waku.lightPush.send`.

The problem with this that sending the message fails, but even though I have a try..catch around `send` the exception is generated at top level as an uncaught rejection. This indicates that there is a promise call somewhere under `send` which is rejected but the error is not handled, so it bubbles up.

It makes it very difficult to detect if sending fails so that it can be retried at the right context in the code. In Node.js you can install a top-level handler for unhandled rejections, but at that point there is missing context to what failed. Ideally the `send` function should not even generate exceptions, because its API returns an error if there were any, so it should capture all exceptions, including rejected promises.

The root cause of the problem seems to be the same as issue #1563 and I haven't seen it happening with `@waku/sdk` version 0.0.16, only with versions starting from 0.0.17.

## Notes

@waku/sdk version 0.0.17, 0.0.18, 0.0.19 (the latest working that I tried was 0.0.16)
Node.js v18.17.1 on Linux
Connected to nwaku 0.18

```

Error: Failed to get a connection to the peer
    at StreamManager.newStream (/home/attila/Projects/LogosLab/waku-objects-playground-bot/node_modules/.pnpm/@waku+core@0.0.23_@multiformats+multiaddr@12.1.3_libp2p@0.46.10/node_modules/@waku/core/src/lib/stream_manager.ts:52:13)
    at StreamManager.prepareNewStream (/home/attila/Projects/LogosLab/waku-objects-playground-bot/node_modules/.pnpm/@waku+core@0.0.23_@multiformats+multiaddr@12.1.3_libp2p@0.46.10/node_modules/@waku/core/src/lib/stream_manager.ts:58:32)
    at StreamManager.getStream (/home/attila/Projects/LogosLab/waku-objects-playground-bot/node_modules/.pnpm/@waku+core@0.0.23_@multiformats+multiaddr@12.1.3_libp2p@0.46.10/node_modules/@waku/core/src/lib/stream_manager.ts:37:10)
    at LightPush.getStream (/home/attila/Projects/LogosLab/waku-objects-playground-bot/node_modules/.pnpm/@waku+core@0.0.23_@multiformats+multiaddr@12.1.3_libp2p@0.46.10/node_modules/@waku/core/src/lib/base_protocol.ts:40:31)
    at <anonymous> (/home/attila/Projects/LogosLab/waku-objects-playground-bot/node_modules/.pnpm/@waku+core@0.0.23_@multiformats+multiaddr@12.1.3_libp2p@0.46.10/node_modules/@waku/core/src/lib/light_push/index.ts:107:33)
    at Array.map (<anonymous>)
    at LightPush.send (/home/attila/Projects/LogosLab/waku-objects-playground-bot/node_modules/.pnpm/@waku+core@0.0.23_@multiformats+multiaddr@12.1.3_libp2p@0.46.10/node_modules/@waku/core/src/lib/light_push/index.ts:105:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at sendMessage (/home/attila/Projects/LogosLab/waku-objects-playground-bot/src/lib/adapters/waku/waku.ts:117:20)
    at safeSendMessage (/home/attila/Projects/LogosLab/waku-objects-playground-bot/src/lib/adapters/waku/bot.ts:343:12)

```

### PR DESCRIPTION
**Pull request by fryorcraken**
Resolves #1569

### CODE REVIEW

**Comment by fryorcraken** [comment]
@fbarbu15 @weboko 

The test I added reproduces #1569 because of the following log line:
`(node:347036) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 12)`

and I can confirm the fix does remove this top level exception.

However, I tried in several manner to catch the exception in the test so that the test could fail when the exception is raised but to no avail. Do you have any suggestion?

**Comment by fbarbu15** [comment]
> @fbarbu15 @weboko
> 
> The test I added reproduces #1569 because of the following log line: `(node:347036) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 12)`
> 
> and I can confirm the fix does remove this top level exception.
> 
> However, I tried in several manner to catch the exception in the test so that the test could fail when the exception is raised but to no avail. Do you have any suggestion?

Tried multiple ways to catch the promise rejection but was only able to do it by checking the stderr. Might be another way but I'm no js expert.
Here's the code that worked for me

 ```
   it.only("Does not throw an exception when node disconnects", async function () {
      this.timeout(20_000);
      this.retries(0);

      const interceptedOutput: string[] = [];

      // Intercept and capture standard error
      const originalWrite = process.stderr.write.bind(process.stderr);

      (process.stderr.write as any) = (
        chunk: any,
        encoding?: any,
        callback?: any
      ): boolean => {
        interceptedOutput.push(chunk.toString());
        originalWrite(chunk, encoding, callback);
        return true;
      };

      nwaku = new NimGoNode(makeLogFileName(this));
      await nwaku.start({
        filter: true,
        store: true,
        lightpush: true
      });
      const multiAddrWithId = await nwaku.getMultiaddrWithId();

      waku = await createLightNode({
        staticNoiseKey: NOISE_KEY_1
      });
      await waku.start();
      await waku.dial(multiAddrWithId);
      await nwaku.stop();
      await waku.lightPush?.send(TestEncoder, {
        payload: utf8ToBytes("hello world")
      });
      await delay(1000);

      // Stop intercepting the sderr
      process.stderr.write = originalWrite;

      // Check if the desired output line is in the intercepted output
      if (
        interceptedOutput.some((line) =>
          line.includes("PromiseRejectionHandledWarning")
        )
      ) {
        throw new Error(
          "Detected PromiseRejectionHandledWarning in the output"
        );
      }
    });
```

**Comment by fryorcraken** [comment]
I was able to detect the top level promise rejection and make the test fail based on it with:

```
      process.on("unhandledRejection", (e) =>
        expect.fail("unhandledRejection", e)
      );
      process.on("uncaughtException", (e) =>
        expect.fail("uncaughtException", e)
      );
```

@fbarbu15 it may be worth checking if we could have this piece of code present on **all** tests to ensure that Waku does not have any uncaught exception or unhandled rejection.

**Review by weboko — APPROVED** [review]

**Comment by weboko** [comment]
Another way to catch promise rejection that is not popping out and is somewhere deep in the code - I think fake promise can be used (if I properly understood the problem). It depends on the testing stack and I am not sure how to handle it in mocha/chai. 

Can research though

**Comment by fbarbu15** [comment]
> I was able to detect the top level promise rejection and make the test fail based on it with:
> 
> ```
>       process.on("unhandledRejection", (e) =>
>         expect.fail("unhandledRejection", e)
>       );
>       process.on("uncaughtException", (e) =>
>         expect.fail("uncaughtException", e)
>       );
> ```
> 
> @fbarbu15 it may be worth checking if we could have this piece of code present on **all** tests to ensure that Waku does not throw any uncaught exception or unhandled rejection.

I had a look at this and unfortunately this is making mocha exit with code 7 and stop execution of other tests. Also no test report is shown. I don't think this is what we want.

```
/home/fbarbu15/WORK_DIR/js-waku/node_modules/chai/lib/chai/interface/expect.js:41
    throw new chai.AssertionError(message, {
    ^
AssertionError: expect.fail()
    at process.<anonymous> (file:///home/fbarbu15/WORK_DIR/js-waku/packages/tests/tests/waku.node.spec.ts:77:16)
    at process.emit (node:events:526:35)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/home/fbarbu15/WORK_DIR/js-waku/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
    at process._fatalException (node:internal/process/execution:149:25) {
  showDiff: false,
  actual: 'uncaughtException',
  expected: AssertionError: expect.fail()
      at process.<anonymous> (file:///home/fbarbu15/WORK_DIR/js-waku/packages/tests/tests/waku.node.spec.ts:74:16)
      at process.emit (node:events:514:28)
      at process.emit (node:domain:489:12)
      at process.emit.sharedData.processEmitHook.installedValue [as emit] (/home/fbarbu15/WORK_DIR/js-waku/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
      at process.Runner.unhandled (/home/fbarbu15/WORK_DIR/js-waku/node_modules/mocha/lib/runner.js:192:19)
      at process.emit (node:events:526:35)
      at process.emit (node:domain:489:12)
      at process.emit.sharedData.processEmitHook.installedValue [as emit] (/home/fbarbu15/WORK_DIR/js-waku/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
      at emit (node:internal/process/promises:149:20)
      at processPromiseRejections (node:internal/process/promises:283:27)
      at processTicksAndRejections (node:internal/process/task_queues:96:32) {
    showDiff: false,
    actual: 'unhandledRejection',
    expected: Error: Failed to get a connection to the peer
        at StreamManager.newStream (file:///home/fbarbu15/WORK_DIR/js-waku/packages/core/src/lib/stream_manager.ts:52:13)
        at StreamManager.prepareNewStream (file:///home/fbarbu15/WORK_DIR/js-waku/packages/core/src/lib/stream_manager.ts:58:32)
        at StreamManager.handlePeerUpdateStreamPool (file:///home/fbarbu15/WORK_DIR/js-waku/packages/core/src/lib/stream_manager.ts:66:12)
        at EventEmitter.[nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20)
        at EventEmitter.dispatchEvent (node:internal/event_target:683:26)
        at EventEmitter.dispatchEvent (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/@libp2p/interface/src/events.ts:63:26)
        at EventEmitter.Libp2pNode.events.dispatchEvent (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/libp2p/src/libp2p.ts:65:30)
        at EventEmitter.safeDispatchEvent (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/@libp2p/interface/src/events.ts:78:17)
        at PersistentPeerStore.#emitIfUpdated (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/@libp2p/peer-store/src/index.ts:212:19)
        at PersistentPeerStore.patch (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/@libp2p/peer-store/src/index.ts:137:26)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/libp2p/src/connection-manager/dial-queue.ts:241:13
        at async DefaultConnectionManager.openConnection (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/libp2p/src/connection-manager/index.ts:516:24)
        at async queue.add.peerId (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/libp2p/src/connection-manager/auto-dial.ts:266:9)
        at async file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/p-queue/dist/index.js:118:36,
    operator: undefined,
    uncaught: true
  },
  operator: undefined
}

Node.js v18.17.1
Mocha tests exited with code 7
npm ERR! Lifecycle script `test:node` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @waku/tests@0.0.1 
npm ERR!   at location: /home/fbarbu15/WORK_DIR/js-waku/packages/tests 
```

**Pull request merged**
